language: php

php:
  - 7.1
  - 7.2

before_script:
  - rm composer.lock
  - composer install --no-interaction --prefer-source
  - php artisan config:clear

script:
 - vendor/bin/phpunit --group=passing

# https://docs.travis-ci.com/user/notifications
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
